dice-group/Ontolearn

README.md
ontolearn/__init__.py
ontolearn/endpoint/simple_drill_endpoint

- Fix drill endpoint
- Example in README

Release Ontolearn 0.2.1

---

.github/workflows/test.yml
environment.yml
setup.cfg
tox.ini

ensure test data exists when running tox

---

examples/dl_learner.py
ontolearn/binders.py

DLLearnerBinder fixed.

---

big_gitext/verify_big.sh

better error message in verify script if server not reachable

---

ontolearn/base_concept_learner.py
ontolearn/knowledge_base.py

- Fixes the prediction function in the BaseConceptLearner

Fix prediction in BaseConceptLearner

---

ontolearn/__init__.py

- Continue development
- Ontolearn 0.3.1

Release Ontolearn 0.3.1

---

examples/sml_bench.py
ontolearn/__init__.py

- fix sml_bench
- Ontolearn 0.3.2

Release Ontolearn 0.3.2

---

ontolearn/abstracts.py
ontolearn/concept_learner.py
ontolearn/knowledge_base.py
ontolearn/learning_problem_generator.py

- add a repr for knowledge base
- rename cl => concept_len, more clear

some usabiliy enhancements

---

ontolearn/__init__.py

- Ontolearn 0.4.0
- Continue development

Continue development

---

ontolearn/abstracts.py
ontolearn/concept_learner.py
ontolearn/learning_problem.py
ontolearn/sparqlkb.py
ontolearn/tentris.py

work on improving the type of an encoded learning problem in tentris+sparql

---

owlapy/parser.py
owlapy/render.py
tests/test_owlapy_parser.py

- Added DLSyntaxParser + tests
- Since there is no official grammar (atleast I did not find one), there might be things we want/have to update later

DL Syntax Parser

---

big_gitext/download_big.sh
big_gitext/download_nces_data
big_gitext/upload_big.sh
big_gitext/verify_big.sh
docs/index.rst
docs/usage/01_knowledge_base.md
docs/usage/02_learning_problem.md
docs/usage/03_ontologies.md
docs/usage/04_reasoner.md
docs/usage/05_concept_learners.md
docs/usage/06_reasoning_details.md
docs/usage/09_model_adapter.md
ontolearn/knowledge_base.py
owlapy/fast_instance_checker.py
owlapy/owlready2/_base.py
owlapy/owlready2/complex_ce_instances.py

- Added "isolate" argument for reasoner to isolate ontologies when using multiple reasoners in the same script.
- Documentation update - added a new page that has details about the new reasoner + some other changes.
- Changed the old ftp link with the new one.

Reasoner adjusments

---

examples/concept_learning_evaluation.py
ontolearn/heuristics.py
ontolearn/learners/__init__.py
ontolearn/learners/drill.py
ontolearn/learners/tree_learner.py

Outperforms all other models. To reproduce please run [concept_learning_evaluation.py](https://github.com/dice-group/Ontolearn/blob/master/examples/concept_learning_evaluation.py)
DRILL is untrained.
```
LP  F1-OCEL  RT-OCEL  F1-CELOE  RT-CELOE  F1-EvoLearner  RT-EvoLearner  F1-DRILL  RT-DRILL  F1-DTL   RT-DTL
0              Aunt  0.80392  3.09363   0.80392   3.03491        0.83673       17.38867   0.96471   4.06782     1.0  2.79888
1           Brother  1.00000  0.03275   1.00000   0.01085        1.00000        0.09431   1.00000   1.36090     1.0  1.79783
2            Cousin  0.69268  3.00510   0.72626   3.01417        0.75132       17.95684   0.34783   1.16468     1.0  4.60511
3     Granddaughter  1.00000  0.03037   1.00000   0.01227        1.00000        0.11953   1.00000   2.31431 …
```

Tree Learner is completed

---

README.md
examples/concept_learning_evaluation.py
ontolearn/abstracts.py
ontolearn/base_concept_learner.py
ontolearn/concept_learner.py
ontolearn/knowledge_base.py
ontolearn/learners/drill.py
ontolearn/learners/tree_learner.py
ontolearn/model_adapter.py
ontolearn/refinement_operators.py
ontolearn/search.py
ontolearn/utils/static_funcs.py
tests/test_base_concept_learner.py
tests/test_concept.py
tests/test_evolearner.py
tests/test_express_refinement.py
tests/test_knowledge_base.py
tests/test_learners_regression.py
tests/test_model_adapter.py

1. Use typing.Callable instead of `Factory=Callable`
2. Max runtime does not behave same between learners, i.e., some models ignore this stooping criterion, some terminates before reaching it

Refactoring

---

examples/concept_learning_cv_evaluation.py
examples/concept_learning_evaluation.py
ontolearn/knowledge_base.py
ontolearn/learners/tree_learner.py

1. Tree-based DL learner implemented
2. Verbalizing a DL concept via llm is available (refactoring needed)
3. Stratified CV script to evaluate learners

tDL, Verbalization, and CV

---

ontolearn/concept_learner.py
tests/test_evolearner.py

- EvoLearner now resets for each call of fit, clearing every stored value that might interfere with the hypothesis generation.
- Updated the Evolearner regression test

EvoLearner bug fixed 

---

ontolearn/refinement_operators.py

Nominals fix

---

.gitignore
examples/concept_learning_cv_evaluation.py

**Added automatic download and mapping for NCES and CLIP embeddings.** 
~@Demirrr can you please check if it runs successfully on a Linux machine before merging?~
For Windows it works correctly!
(Edit) I checked it on a Linux VM. It works correctly for Linux as well.

Evaluation setup for NCES and CLIP

---

README.md
ontolearn/knowledge_base.py
ontolearn/learners/drill.py
ontolearn/refinement_operators.py
ontolearn/search.py

https://github.com/dice-group/Ontolearn/issues/404 is adressed

Default cardinality restriction

---

ontolearn/owl_neural_reasoner.py

Changed all values from implementation to be equivalent to approach from paper/thesis

Neural reasoner all values from

---

ontolearn/owl_neural_reasoner.py

Prediciton caching with dynamic cache size + caching is optional
